### ISSUE TITLE
`Datatype not supported` with scipy

### ISSUE THREAD

**Issue by caspervdw** [hgomersall/pyFFTW#56] opened 2015-02-02 20:03 UTC
Hi,

I am working with trackpy for particle tracking and it has an optionality to use pyfftw for bandpass filters. On my windows (64-bit) box, I get a `RuntimeError: datatype not supported`, when I run a gaussian filter on the FFTd image. I can reproduce the problem as follows:

    import numpy as np
    import pyfftw
    from scipy.ndimage.fourier import fourier_gaussian
    
    a = np.random.randint(0, 256, (50,50))
    a = pyfftw.n_byte_align(a, a.dtype.alignment)
    afftw = pyfftw.interfaces.numpy_fft.fftn(a)
    
    fourier_gaussian(afftw, (1., 1.))  # RuntimeError: data type not supported

Copying the afftw to a new empty numpy array solves the problem. The difference I can see between `afftw` and an FFT which was produced by `numpy.fft` is that pyfftw has `strides == (800L, 16L)` whereas the numpy one has `strides == (16L, 800L)`. But both should work with scipy, and transposing or asfortranarray or ascontiguousarray doesn't help.

See also https://github.com/soft-matter/trackpy/issues/198

**Comment by hgomersall** [comment] 2015-02-02 21:03
Your code actually works for me. What version of scipy are you using? It _sounds_ like a scipy bug that has been fixed. It's possible I've fixed it in my installation of pyfftw, but I'd be surprised if it's that. You can install pyfftw from git - i've been meaning to make a release anyway for a while.

**Comment by hgomersall** [comment] 2015-02-02 21:06
There is an interesting point here whether pyfftw should always return what numpy returns when using the numpy interface. It clearly doesn't at the moment, but always adding a copy is suboptimal. Perhaps a module level configure option...

**Comment by caspervdw** [comment] 2015-02-03 14:57
Thanks for the response. I was using scipy 0.14.0, if I update to 0.15.1, there is no error message, it just hangs. PyFFTW is version 0.9.2, I used the binary from pypi.

I will try to compile the newest version from git.

**Comment by hgomersall** [comment] 2015-02-03 15:09
Do you have a comment on the correct behaviour? _Should_ the interfaces routine return what is returned by numpy?

**Comment by caspervdw** [comment] 2015-02-03 21:29
I think that such a behaviour for the interfaces routine would be great. If
the user really wants to be as fast as possible, he shouldnt use the
interfaces routine, right?

Op dinsdag 3 februari 2015 heeft Henry Gomersall <notifications@github.com>
het volgende geschreven:

**Comment by caspervdw** [comment] 2015-02-17 09:53
I've tested it with 0.10.0 from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyfftw, and the problem still persists. I did make some progress: setting the dtype of the numpy array again solves the problem:

    fourier_gaussian(afftw, (1., 1.))  # errors
    fourier_gaussian(afftw.astype(np.complex128), (1., 1.))  # passes

While afftw already is of the type `np.complex128`.

**Comment by hgomersall** [comment] 2015-02-17 10:06
I think the issue is likely not pyfftw in this case, but Scipy. Did you upgrade that too? I'm intrigued that pyfftw 0.10.0 is on Christoph Gohlke's page already - it's not actually released so it must be built from github.

**Comment by pijyoi** [comment] 2015-06-04 09:14
I am using pyfftw 0.9.2 on WinPython 3.4.3.3 64-bits
The following snippet produces as output "G D".
The question is why an input of float64 should produce an output of type "complex long double" (even though on Microsoft compilers, long double is the same size as double)  

```python
import numpy as np
import pyfftw

a1 = np.empty(4, dtype=np.float64)
a2 = np.empty(4, dtype=np.complex128)
fftobj1 = pyfftw.builders.fft(a1)
fftobj2 = pyfftw.builders.fft(a2)
a1[:] = [1,2,3,4]
a2[:] = [1,2,3,4]
b1 = fftobj1()
b2 = fftobj2()
print(b1.dtype.char, b2.dtype.char)
```

**Comment by hgomersall** [comment] 2015-06-04 09:18
@pijyoi If you think this is a bug, can you raise it in its own issue; I'm pretty sure your problem has nothing to do with this issue.

**Comment by pijyoi** [comment] 2015-06-04 09:38
Running @caspervdw 's snippet, I do get the same error.

The following also raises a runtime error on my system w/o having involved pyfftw.
```python
fourier_gaussian(np.zeros((50,50), dtype='G'), (1.,1.))
```

**Comment by hgomersall** [comment] 2015-06-04 09:46
@pijyoi I really can't help with issues with scipy :(

**Comment by pijyoi** [comment] 2015-06-04 10:00
IMO, it's not a bug of scipy that fourier_gaussian doesn't support dtype 'G'.

It is however surprising behaviour of pyfftw that an input of dtype 'd' produces not an output of dtype 'D' but instead an output of dtype 'G'.

At least it does so on Win64. I could try it on a Linux platform to see if it's any different.

**Comment by hgomersall** [comment] 2015-06-04 10:03
It is different on linux. Can we use the dtype rather than the dtype.char. D and G mean nothing to me.

**Comment by pijyoi** [comment] 2015-06-04 10:22
f is float32. F is complex64.
d is float64. D is complex128.
G is supposed to be "complex long double" except that with MSVC it maps to complex128.

So an input of float64 yielded an output of type char corresponding to "complex long double".

**Comment by hgomersall** [comment] 2015-06-04 10:42
This is interesting. If you're getting 'complex128', then no issue.

[I probed this a bit some time ago](http://stackoverflow.com/questions/9062562/what-is-the-internal-precision-of-numpy-float128). So if you're saying MSVC maps it to complex128, what does the dtype report as?

**Comment by pijyoi** [comment] 2015-06-04 11:05
I will check it out when I get access to my win64 system tomorrow. 

Meanwhile: "long double" equals "double" on Microsoft compilers reference:
https://msdn.microsoft.com/en-us/library/cc953fe1.aspx

**Comment by hgomersall** [comment] 2015-06-04 11:24
@pijyoi Ok, so it might be that this is just a non-issue caused by peculiarities with MSVC and it's double/long-double synonym.

**Comment by caspervdw** [comment] 2015-06-04 20:34
The `astype(np.complex128)` does solve the issue and doesn't cost you a lot if it's already of the right type. It may be worth it to implement this in the numpy interface.

**Comment by pijyoi** [comment] 2015-06-05 00:05
Okay, so the problem appears to arise from the lookup table _rc_dtype_pairs in builders/_utils.py.
There are 6 entries in the source but the resulting dictionary has only 4 entries on Win64 due to duplicate keys.

The problem is that we have the following properties on Win64:
```python
np.dtype('float64') == np.dtype('longdouble')
np.dtype('float64').type == np.dtype('longdouble').type    # numpy.float64
np.dtype('float64').char != np.dtype('longdouble').char    # 'd' != 'g'

np.dtype('complex128') == np.dtype('clongdouble')
np.dtype('complex128').type == np.dtype('clongdouble').type   # numpy.comlex128
np.dtype('complex128').char != np.dtype('clongdouble').char   # 'D' != 'G'
```

This is arguably a numpy bug but a simple workaround for pyfftw would be to populate the table with longdouble and clongdouble entries only if they differ from float64 and complex128 respectively?

**Comment by hgomersall** [comment] 2015-06-05 07:00
Interesting. So the problem is the lookup is using the wrong dtype on MSVC?

Can you confirm which lookup is wrong? Is the hash of the dtypes the same? It might be enough to convert the dtype to a str().

**Comment by pijyoi** [comment] 2015-06-05 07:23
The following are both true on Win64 (compiled with MSVC):
hash(np.dtype('float64'))==hash(np.dtype('longdouble'))
hash(np.dtype('complex128'))==hash(np.dtype('clongdouble'))

The resulting (4-entry) lookup table is equivalent to:
np.dtype('float32') -> np.dtype('complex64')
np.dtype('longdouble') -> np.dtype('clongdouble')
np.dtype('complex64') -> np.dtype('float32')
np.dtype('clongdouble') -> np.dtype('longdouble')

a lookup of np.dtype('float64') then returns np.dtype('clongdouble')
similarly, a lookup of np.dtype('complex128') returns np.dtype('longdouble')

The problem doesn't appear for Windows 32-bit though. NumPy on that platform has float96 for storage although it is only computed as float64. The following old thread explains it:
http://mail.scipy.org/pipermail/numpy-discussion/2011-November/059257.html

**Comment by hgomersall** [comment] 2015-06-05 07:30
Can you print out `builders._utils._rc_dtype_pairs`? The creation should be stripping out one of the entries if the hashes match.

**Comment by pijyoi** [comment] 2015-06-05 07:45
It's
```python
{dtype('float32'): dtype('complex64'),
 dtype('complex64'): dtype('float32'),
 dtype('float64'): dtype('complex128'),
 dtype('complex128'): dtype('float64')}
```

The above printout masks the problem. Printing out the char code shows the problem.
Expected output should have been pairs of lowercase/uppercase of the same letter. 
```python
print([(k.char,v.char) for k,v in pyfftw.builders._utils._rc_dtype_pairs.items()])
[('F', 'f'), ('D', 'g'), ('f', 'F'), ('d', 'G')]
```

**Comment by hgomersall** [comment] 2015-06-05 08:03
So does dtype('longdouble') on windows show as dtype('float64')? I mean, is it possible to have an array that is dtype('longdouble')?

**Comment by pijyoi** [comment] 2015-06-05 08:25
```python
a = np.dtype('longdouble')
b = np.dtype('float64')
print(repr(a), a.char)   # dtype('float64') g
print(repr(b), b.char)   # dtype('float64') d
```
The distinguishing feature is the char code...

**Comment by hgomersall** [comment] 2015-06-05 09:24
Ok, so it seems the solution is to use the dtype.char as the keys in the dictionary. I think this would fix all cases?

**Comment by pijyoi** [comment] 2015-06-05 09:40
Yes, that should fix the root cause that dtypes are not suitable as dictionary keys.

**Comment by hgomersall** [comment] 2015-06-05 10:29
I've just pushed 9907acfdf9389648946b3085b47168387d5040a1 which should fix this. It would be great if you can try it out. Firstly though, it would be really helpful to me if you can confirm the new test actually picks up the problem (`test.test_pyfftw_builders.BuildersTestFFT.test_output_dtype_correct`). This _should_ fail under windows, and pass with the new `_utils.py`.

**Comment by pijyoi** [comment] 2015-06-05 11:46
Will do next week when I get access to my win64 system. Thanks for the fix.

**Comment by hgomersall** [comment] 2015-06-05 11:52
No rush (we're at least no worse off than we were!)

**Comment by pijyoi** [comment] 2015-06-08 08:56
The new _utils.py does fix the problem.
In particular, @caspervdw 's original snippet now runs without error.

However the new test does not pick up the problem. It succeeds with both the old and new _utils.py.

**Comment by hgomersall** [comment] 2015-06-08 09:16
Ok, so now I'm just confused. I thought the whole issue was that the dtype.char is not returning the correct value for different results. How are you running the test? The test *is* using the old code?

**Comment by pijyoi** [comment] 2015-06-08 09:49
Not sure if it matters, but first I uninstall pyfftw.

Checkout master.
Copy test_pyfftw_builders.py to some temporary folder.
Create branch "newtest" at 6ecb7a.
Copy and commit the new test_pyfftw_builders.py to this branch.

So branch newtest has the old _utils.py but the new test.

I run the following script under ipython (inside the pyFFTW folder) for both branch master and branch newtest.
```python
import test.test_pyfftw_builders
x = test.test_pyfftw_builders.BuildersTestFFT()
x.test_output_dtype_correct()

import pyfftw
import numpy as np
a = np.zeros(4, dtype=np.float64)
fftobj = pyfftw.builders.fft(a)
b = fftobj()
print(a.dtype.char, b.dtype.char)
```

branch newtest: no assertion. outputs "d G" # float64 --> clongdouble
branch master: no assertion. outputs "d D"  # float64 --> complex128

**Comment by hgomersall** [comment] 2015-06-08 14:37
Hmm, this test is actually harder to implement than I thought. I think the MSVC case needs to be special cased... fancy a bash?

**Comment by pijyoi** [comment] 2015-06-08 18:09
I browsed through the test code. For the fft, fft2, fftn functions, the code only tests complex input and output. The case where the input is real is not tested.

**Comment by hgomersall** [comment] 2015-06-08 21:36
Ah yes, so it needs to be like test_dtype_coercian. I'm still not sure it will pick it up. I'm sorry, I'm not giving it the attention I need in order to work it out properly - I'm really busy at the moment.

**Comment by pijyoi** [comment] 2015-06-09 05:08
I changed make_real_data() to the following:
```python
def make_real_data(shape, dtype):
    return numpy.random.randn(*shape).astype(dtype)
```
and
```python
functions['fft'] = 'r2c'
```

Then on Win64, the test asserts on the old _utils.py but succeeds on the new _utils.py.

The first change is because:
```python
np.longdouble(np.random.randn(4,4).dtype.char=='d'
np.random.randn(4,4).astype(np.longdouble).dtype.char=='g'
```

This is just a quickie test to check that it does pick up the problem. Not sure how we could specify that the fft, fft2, fftn functions can take both real and complex input.

**Comment by hgomersall** [comment] 2015-06-10 15:50
Interesting. I think it should be safe to use your first fix.

The second is not too hard to put in. The issue is that we just want to check all the various inputs agree with all the various outputs. Possibly ignore `input_dtypes` and check all the inputs (`output_dtypes` should still be useful though).

**Comment by pijyoi** [comment] 2015-06-11 05:43
It seems that casting using the dtype returns the original array if deemed that no change was needed. So what I originally thought was an inconsistency in NumPy isn't one after all.
```python
z = np.zeros(4)
x = np.longdouble(z) # x is z
y1 = z.astype(np.longdouble, copy=False) # y1 is z
y2 = z.astype(np.longdouble) # y2 is not z
```

**Comment by hgomersall** [comment] 2015-09-25 09:13
This is being highlighted now we're (beginning) to use Appveyor - all the windows tests are failing on this one.

**Comment by hgomersall** [comment] 2015-10-15 17:14
I think this is fixed with d49a326. Agreement?

**Comment by pijyoi** [comment] 2015-10-16 05:44
Yes. Can be closed I think.
The original code snippet by @caspervdw works fine now under Win64.

**Comment by caspervdw** [comment] 2015-10-16 05:59
Thanks for solving!
Op 16 okt. 2015 07:44 schreef "pijyoi" <notifications@github.com>:

**Closed** 2015-10-16 06:45 UTC
